apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo-banking-validation
spec:
  selector:
    matchLabels:
      role: mongo
      environment: prod
  serviceName: "mongo-banking-validation"
  replicas: 3
  template:
    metadata:
      labels:
        role: mongo
        environment: prod
    spec:
      serviceAccountName: pod-reader-sa
      terminationGracePeriodSeconds: 10
      containers:
      - name: mongo-banking-validation
        image: mongo
        envFrom:
        - secretRef:
            name: mongo-banking-validation
        command:
          - mongod
          - "--replSet"
          - rs0
        ports:
          - containerPort: 27017
        volumeMounts:
          - name: mongo-persistent-storage
            mountPath: /data/db
      - name: mongo-sidecar
        image: cvallance/mongo-k8s-sidecar:latest
        env:
          - name: MONGO_SIDECAR_POD_LABELS
            value: "role=mongo,environment=prod"
          - name: MONGODB_USERNAME
            value: "admin-banking"
          - name: MONGODB_PASSWORD
            value: "harnessbankingdemo"
          - name: KUBE_NAMESPACE
            value: prod
          - name: KUBERNETES_MONGO_SERVICE_NAME
            value: mongo-banking-validation
  volumeClaimTemplates:
    - metadata:
        name: mongo-persistent-storage
      spec:
        storageClassName: "fast"
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 2Gi
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: fast
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-ssd
volumeBindingMode: Immediate
---
apiVersion: v1
kind: Secret
metadata:
  name: mongo-banking-validation
stringData:
  MONGODB_PASSWORD: "harnessbankingdemo"
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: prod
  name: pod-reader
rules:
- apiGroups: ["*"] # "" indicates the core API group
  # - rbac.authorization.k8s.io
  # - roles.rbac.authorization.k8s.io
  # - authorization.k8s.io
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pod-reader-cr
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pod-reader
subjects:
  - kind: ServiceAccount
    name: pod-reader-sa
    namespace: prod
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pod-reader-sa
automountServiceAccountToken: true