apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo-banking-validation
spec:
  selector:
    matchLabels:
      role: mongo
      environment: prod
  serviceName: "mongo-banking-validation"
  replicas: 3
  template:
    metadata:
      labels:
        role: mongo
        environment: prod
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: mongo-banking-validation
        image: mongo
        envFrom:
        - secretRef:
            name: mongo-banking-validation
        command:
          - mongod
          - "--replSet"
          - rs0
          - "--noprealloc"
        ports:
          - containerPort: 27017
        volumeMounts:
          - name: mongo-persistent-storage
            mountPath: /data/db
      - name: mongo-sidecar
        image: cvallance/mongo-k8s-sidecar
        env:
          - name: MONGO_SIDECAR_POD_LABELS
            value: "role=mongo,environment=test"
          - name: MONGODB_USERNAME
            value: "admin-banking"
  volumeClaimTemplates:
    - metadata:
        name: mongo-persistent-storage
      spec:
        storageClassName: "fast"
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 2Gi
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: fast
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-ssd
volumeBindingMode: Immediate
---
apiVersion: v1
kind: Secret
metadata:
  name: mongo-banking-validation
data:
  MONGODB_PASSWORD: "harnessbankingdemo"
---
