apiVersion: v1
kind: Service
metadata:
  name: mongo-banking-validation
  labels:
    name: -banking-validation
spec:
  ports:
    - port: 27017
      targetPort: 27017
  clusterIP: None
  selector:
    role: mongo