apiVersion: v1
kind: Service
metadata:
  name: mongo-banking-validation
  labels:
    name: mongo-banking-validation
spec:
  ports:
    - port: 27017
      targetPort: 27017
  type: ClusterIP
  selector:
    role: mongo
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mongo-banking-ingress
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
  - host: payments-validation-mongo.harness-demo.site
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: mongo-banking-validation
            port:
              number: 27017