apiVersion: v1
kind: Service
metadata:
  name: mongo-banking-validation
  labels:
    name: mongo-banking-validation
spec:
  ports:
    - port: 27017
      targetPort: 27017
  type: ClusterIP
  selector:
    role: mongo