pipeline:
  name: CD - Serverless Deployment - DONT USE IT
  identifier: CD_Serverless_Deployment
  projectIdentifier: GIT_FLOW_DEMO
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: Build NodeJS
        identifier: Build_NodeJS
        type: CI
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  name: Build NodeJS
                  identifier: Build_NodeJS
                  spec:
                    shell: Sh
                    command: |-
                      echo "Build"

                      echo '<+pipeline.variables.trigger_payload>'
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
  properties:
    ci:
      codebase:
        connectorRef: diegoengbitbucket
        repoName: diegokoala/serverless-function
        build: <+input>
  variables:
    - name: trigger_payload
      type: String
      description: ""
      required: false
      value: <+input>
