pipeline:
  name: CD - Terraform Sonar Deploy AWS
  identifier: CD_Terraform_Sonar_Deploy_AWS
  projectIdentifier: GIT_FLOW_DEMO
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: Deploy Sonar Terraform
        identifier: Deploy_Sonar_Terraform
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: TerraformPlan
                  name: Terraform Plan Deploy Sonar
                  identifier: TerraformPlan_1
                  spec:
                    provisionerIdentifier: sonartf
                    configuration:
                      command: Apply
                      configFiles:
                        store:
                          spec:
                            connectorRef: account.diegogithubapp
                            repoName: terraform-templates
                            gitFetchType: Branch
                            branch: main
                            folderPath: aws/sonar
                          type: Github
                      backendConfig:
                        type: Inline
                        spec:
                          content: |-
                            bucket = "diego-aws-storage"
                            key    = "tf_state_files/sonartf"
                            region = "us-east-1"
                      environmentVariables:
                        - name: AWS_ACCESS_KEY_ID
                          value: <+secrets.getValue('AWS_ACCESS_KEY_ID')>
                          type: String
                        - name: AWS_SECRET_ACCESS_KEY
                          value: <+secrets.getValue('AWS_SECRET_ACCESS_KEY')>
                          type: String
                      secretManagerRef: harnessSecretManager
                      workspace: prod
                      exportTerraformHumanReadablePlan: true
                      skipRefreshCommand: false
                  timeout: 10m
              - step:
                  type: TerraformApply
                  name: Terraform Apply Deploy Sonar
                  identifier: Terraform_Apply_Deploy_Sonar
                  spec:
                    provisionerIdentifier: sonartf
                    configuration:
                      type: InheritFromPlan
                  timeout: 10m
        tags: {}
