pipeline:
  name: DAST
  identifier: DAST
  projectIdentifier: GIT_FLOW_DEMO
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: DAST Tests
        identifier: DAST_Tests
        type: SecurityTests
        spec:
          cloneCodebase: false
          execution:
            steps:
              - step:
                  type: Run
                  name: Docker Service
                  identifier: Docker_Service
                  spec:
                    connectorRef: account.DockerHubDiego
                    image: docker:dind
                    shell: Sh
                    command: |-
                      while ! docker ps ;do 
                            echo "Docker not available yet"
                      done
                      echo "Docker Service Ready"
                      docker ps
              - step:
                  type: Security
                  name: OWASP Zap
                  identifier: Security
                  spec:
                    privileged: true
                    settings:
                      policy_type: orchestratedScan
                      scan_type: instance
                      product_name: zap
                      product_config_name: standard
                      instance_identifier: OwaspJavaApp
                      instance_environment: prod
                      instance_domain: payments-validation.harness-demo.site
                      instance_protocol: http
                      instance_port: "80"
                      instance_type: website
                      instance_path: /diegopereiraeng/validation
                    imagePullPolicy: IfNotPresent
                    resources:
                      limits:
                        memory: 1Gi
                        cpu: 500m
                  serviceDependencies:
                    - identifier: DinD
                      name: DinD
                      type: Service
                      spec:
                        connectorRef: account.harnessImage
                        image: docker:dind
          infrastructure:
            useFromStage: Build
          serviceDependencies:
            - identifier: DinD
              name: DinD
              type: Service
              spec:
                connectorRef: account.DockerHubDiego
                image: docker:dind
                privileged: true
                resources:
                  limits:
                    memory: 1Gi
                    cpu: 500m
          sharedPaths:
            - /var/run
            - /var/lib/docker
