pipeline:
    name: Deploy Dev
    identifier: Deploy_Dev
    allowStageExecutions: false
    projectIdentifier: GIT_FLOW_DEMO
    orgIdentifier: default
    tags: {}
    stages:
        - stage:
              name: Deploy Banking App Dev
              identifier: Deploy_Banking_App_Dev
              description: ""
              type: Deployment
              spec:
                  serviceConfig:
                      serviceDefinition:
                          type: Kubernetes
                          spec:
                              artifacts:
                                  sidecars: []
                                  primary:
                                      type: DockerRegistry
                                      spec:
                                          connectorRef: account.DockerHubDiego
                                          imagePath: diegokoala/harness-ff-bankingapp
                                          tag: dev
                              manifestOverrideSets: []
                              manifests:
                                  - manifest:
                                        identifier: K8sBankingApp
                                        type: K8sManifest
                                        spec:
                                            store:
                                                type: Github
                                                spec:
                                                    connectorRef: account.Diego_Git
                                                    gitFetchType: Branch
                                                    paths:
                                                        - templates/envs/dev/deployment.yaml
                                                        - templates/envs/dev/namespace.yaml
                                                        - templates/envs/dev/service.yaml
                                                    repoName: k8s-manifests-templates
                                                    branch: main
                                            skipResourceVersioning: false
                                  - manifest:
                                        identifier: Values
                                        type: Values
                                        spec:
                                            store:
                                                type: Github
                                                spec:
                                                    connectorRef: account.Diego_Git
                                                    gitFetchType: Branch
                                                    paths:
                                                        - values.yaml
                                                    repoName: values-k8s
                                                    branch: main
                              variables: []
                      serviceRef: BankingAppUI
                  infrastructure:
                      environmentRef: dev
                      infrastructureDefinition:
                          type: KubernetesDirect
                          spec:
                              connectorRef: account.cddemose
                              namespace: harness-cd-ff-demo
                              releaseName: banking-app-release-prod
                      allowSimultaneousDeployments: true
                      infrastructureKey: banking-app-k8s
                  execution:
                      steps:
                          - step:
                                type: ShellScript
                                name: Retrieve Secrets
                                identifier: Retrieve_Secrets
                                spec:
                                    shell: Bash
                                    onDelegate: true
                                    source:
                                        type: Inline
                                        spec:
                                            script: |-
                                                
                                                var1='<'
                                                var2='+'
                                                var3='>'
                                                var4='secrets.getValue("account.diegogitapppem")'
                                                var5='secrets.getValue("account.diegogitapppem")'
                                                finalVar="$var1$var2 \"ABC:\" + $var4 $var3"
                                                export finalVar

                                                finalVar2="$var1$var2 \"ABC:\" + $var4 \
                                                \"DEF:\" + $var5 $var3"

                                                finalVar2="$var1$var2 \"ABC: \" + $var4 \
                                                +  \"\\nDEF: \" + $var5 $var3"
                                                export finalVar2

                                                meio='"OUTRO_SECRET:" + secrets.getValue("account.diegogitapppem") + "DATABASE_URL:" +  secrets.getValue("account.diegogitapppem")'
                                                fim=">"
                                                SECRETS_YAML2="TESTE"
                                                export SECRETS_YAML2


                                                echo "<+execution.steps.step.name>"

                                                echo "<+execution.steps.stepGroup.name>"
                                                echo "<+step>"
                                    environmentVariables:
                                        - name: HARNESS_ACCOUNT_ID
                                          type: String
                                          value: oEWs6wr7QvOW8d0ISfhttQ
                                        - name: HARNESS_API_KEY
                                          type: String
                                          value: sat.623a2cd5cf67162d22b9cdbe.OIY82qrwRzgkELLa6PZu
                                    outputVariables:
                                        - name: SECRETS_YAML
                                          type: String
                                          value: finalVar
                                        - name: SECRETS_YAML2
                                          type: String
                                          value: SECRETS_YAML2
                                        - name: finalVar
                                          type: String
                                          value: finalVar
                                        - name: finalVar2
                                          type: String
                                          value: finalVar2
                                    executionTarget: {}
                                timeout: 10m
                                failureStrategies: []
                          - step:
                                type: HarnessApproval
                                name: Approval
                                identifier: Approval
                                spec:
                                    approvalMessage: Please review the following information and approve the pipeline progression
                                    includePipelineExecutionHistory: true
                                    approvers:
                                        userGroups:
                                            - account.Field_Engineering
                                        minimumCount: 1
                                        disallowPipelineExecutor: false
                                    approverInputs: []
                                timeout: 1d
                          - stepGroup:
                                name: Canary Deployment
                                identifier: canaryDepoyment
                                steps:
                                    - step:
                                          name: Canary Deployment
                                          identifier: canaryDeployment
                                          type: K8sCanaryDeploy
                                          timeout: 10m
                                          spec:
                                              instanceSelection:
                                                  type: Count
                                                  spec:
                                                      count: 1
                                              skipDryRun: false
                                    - step:
                                          type: Verify
                                          name: Deployment Verification
                                          identifier: verify_prod
                                          spec:
                                              type: Rolling
                                              spec:
                                                  sensitivity: MEDIUM
                                                  duration: 5m
                                                  deploymentTag: <+serviceConfig.artifacts.primary.tag>
                                          timeout: 2h
                                          failureStrategies:
                                              - onFailure:
                                                    errors:
                                                        - Verification
                                                    action:
                                                        type: ManualIntervention
                                                        spec:
                                                            timeout: 2h
                                                            onTimeout:
                                                                action:
                                                                    type: StageRollback
                                              - onFailure:
                                                    errors:
                                                        - Unknown
                                                    action:
                                                        type: ManualIntervention
                                                        spec:
                                                            timeout: 2h
                                                            onTimeout:
                                                                action:
                                                                    type: Ignore
                                    - step:
                                          name: Canary Delete
                                          identifier: canaryDelete
                                          type: K8sCanaryDelete
                                          timeout: 10m
                                          spec: {}
                                rollbackSteps:
                                    - step:
                                          name: Canary Delete
                                          identifier: canaryDelete
                                          type: K8sCanaryDelete
                                          timeout: 10m
                                          spec: {}
                          - stepGroup:
                                name: Primary Deployment
                                identifier: primaryDepoyment
                                steps:
                                    - step:
                                          name: Rolling Deployment
                                          identifier: rollingDeployment
                                          type: K8sRollingDeploy
                                          timeout: 10m
                                          spec:
                                              skipDryRun: false
                                rollbackSteps:
                                    - step:
                                          name: Rolling Rollback
                                          identifier: rollingRollback
                                          type: K8sRollingRollback
                                          timeout: 10m
                                          spec: {}
                          - step:
                                type: Http
                                name: Health Check
                                identifier: Check_Health
                                spec:
                                    method: GET
                                    headers: []
                                    outputVariables: []
                                    assertion: <+httpResponseCode> == 200
                                    url: http://ff.harness-demo.site/<+pipeline.variables.virtualPath>/index.html
                                timeout: 1m
                                failureStrategies:
                                    - onFailure:
                                          errors:
                                              - AllErrors
                                          action:
                                              type: MarkAsSuccess
                      rollbackSteps: []
                  serviceDependencies: []
              when:
                  pipelineStatus: Success
              failureStrategies:
                  - onFailure:
                        errors:
                            - AllErrors
                        action:
                            type: StageRollback
    variables:
        - name: tag
          type: String
          value: <+input>
        - name: serviceName
          type: String
          value: banking-app
        - name: ffkey
          type: String
          value: <+input>
        - name: virtualPath
          type: String
          value: <+input>
        - name: VirtualPathQA
          type: String
          value: <+pipeline.variables.virtualPath>-qa
        - name: gitEvent
          type: String
          value: <+input>
        - name: target
          type: String
          value: <+input>
        - name: ffkey_prod
          type: String
          value: 44e3ffcb-3a5e-4af1-a7f3-ba7a51cbc74b
