pipeline:
    name: FF Diego
    identifier: FF_Diego
    allowStageExecutions: false
    projectIdentifier: GIT_FLOW_DEMO
    orgIdentifier: default
    tags: {}
    stages:
        - stage:
              name: FF Youtube
              identifier: FF_Youtube
              description: ""
              type: FeatureFlag
              spec:
                  execution:
                      steps:
                          - step:
                                type: FlagConfiguration
                                name: FF Canary
                                identifier: FF_Canary
                                spec:
                                    feature: ALL_YOUTUBE_MODAL
                                    environment: diegopereiraeng
                                    instructions:
                                        - identifier: AddRuleIdentifier
                                          type: AddRule
                                          spec:
                                              priority: 100
                                              distribution:
                                                  clauses:
                                                      - op: segmentMatch
                                                        attribute: ""
                                                        values:
                                                            - Beta_Users
                                                  variations:
                                                      - variation: "OFF"
                                                      - variation: Captain_Canary
                                                        weight: 50
                                                      - variation: Feature_Flags
                                                        weight: 50
                                                  bucketBy: timezone
                                timeout: 10m
