pipeline:
  name: SE AB Pipeline
  identifier: FF_Diego
  allowStageExecutions: false
  projectIdentifier: GIT_FLOW_DEMO
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: FF Youtube
        identifier: FF_Youtube
        description: ""
        type: FeatureFlag
        spec:
          execution:
            steps:
              - step:
                  type: FlagConfiguration
                  name: Youtube AB
                  identifier: FF_Canary
                  spec:
                    feature: ALL_YOUTUBE_MODAL
                    environment: diegopereiraeng
                    instructions: <+input>
                  timeout: 10m
              - step:
                  type: ShellScript
                  name: Collect Feedback from Analytics
                  identifier: Collect_Feedback_from_Analytics
                  spec:
                    shell: Bash
                    onDelegate: true
                    source:
                      type: Inline
                      spec:
                        script: |
                          echo "Collecting Analytics Feedback"

                          canary=35
                          ff=65

                          echo "Conversion rate:"

                          echo "C. Canary:     ${canary}%"
                          echo "Feature Flags: ${ff}%"
                          result="na"
                          if [ "$canary" -gt "$ff" ]; then
                            result="canary"
                          else
                            result="ff"
                          fi

                          export $result
                    environmentVariables: []
                    outputVariables:
                      - name: result
                        type: String
                        value: result
                  timeout: 10m
              - step:
                  type: HarnessApproval
                  name: Approval
                  identifier: Approval
                  spec:
                    approvalMessage: Please review the following information and approve the pipeline progression
                    includePipelineExecutionHistory: true
                    approvers:
                      userGroups:
                        - account.Field_Engineering
                        - account.New_Demo_Group
                        - account.Read_Only_Users
                      minimumCount: 1
                      disallowPipelineExecutor: false
                    approverInputs: []
                  timeout: 1d
              - parallel:
                  - step:
                      type: FlagConfiguration
                      name: FF 100
                      identifier: Youtube_100
                      spec:
                        feature: <+input>
                        environment: diegopereiraeng
                        instructions: <+input>
                      timeout: 10m
                      when:
                        stageStatus: Success
                        condition: <+pipeline.stages.FF_Youtube.execution.steps.Collect_Feedback_from_Analytics.output.outputVariables.result> == "ff"
                      failureStrategies: []
                  - step:
                      type: FlagConfiguration
                      name: Canary 100
                      identifier: Canary_100
                      spec:
                        feature: ALL_YOUTUBE_MODAL
                        environment: diegopereiraeng
                        instructions: <+input>
                      timeout: 10m
                      when:
                        stageStatus: Success
                        condition: <+pipeline.stages.FF_Youtube.execution.steps.Collect_Feedback_from_Analytics.output.outputVariables.result> == "canary"
                      failureStrategies: []
          serviceDependencies: []
  variables:
    - name: environment
      type: String
      default: diegopereiraeng
      description: ""
      value: <+input>.allowedValues(diegopereiraeng,guinogueira7,crizstian,andymarshallff)
