pipeline:
  name: Diego AB Pipeline
  identifier: FF_Diego
  allowStageExecutions: false
  projectIdentifier: GIT_FLOW_DEMO
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: FF Youtube
        identifier: FF_Youtube
        description: ""
        type: FeatureFlag
        spec:
          execution:
            steps:
              - step:
                  type: FlagConfiguration
                  name: Youtube AB
                  identifier: FF_Canary
                  spec:
                    feature: ALL_YOUTUBE_MODAL
                    environment: diegopereiraeng
                    instructions:
                      - identifier: AddRuleIdentifier
                        type: AddRule
                        spec:
                          priority: 100
                          distribution:
                            clauses:
                              - op: segmentMatch
                                attribute: ""
                                values:
                                  - Beta_Users
                            bucketBy: email
                            variations:
                              - variation: "OFF"
                                weight: 0
                              - variation: Captain_Canary
                                weight: 50
                              - variation: Feature_Flags
                                weight: 50
                              - variation: Italika
                                weight: 0
                              - variation: Gabs_GoT
                                weight: 0
                              - variation: Ion
                                weight: 0
                      - identifier: SetFeatureFlagStateIdentifier
                        type: SetFeatureFlagState
                        spec:
                          state: "on"
                  timeout: 10m
              - step:
                  type: ShellScript
                  name: Collect Feedback from Analytics
                  identifier: Collect_Feedback_from_Analytics
                  spec:
                    shell: Bash
                    onDelegate: true
                    source:
                      type: Inline
                      spec:
                        script: |
                          echo "Collecting Analytics Feedback"

                          canary=70
                          ff=35

                          echo "Conversion rate:"

                          echo "C. Canary:     ${canary}%"
                          echo "Feature Flags: ${ff}%"
                          result="na"
                          if [ "$canary" -gt "$ff" ]; then
                            result="canary"
                          else
                            result="ff"
                          fi

                          export $result
                    environmentVariables: []
                    outputVariables:
                      - name: result
                        type: String
                        value: result
                  timeout: 10m
              - step:
                  type: HarnessApproval
                  name: Approval
                  identifier: Approval
                  spec:
                    approvalMessage: Please review the following information and approve the pipeline progression
                    includePipelineExecutionHistory: true
                    approvers:
                      userGroups:
                        - account.Field_Engineering
                        - account.New_Demo_Group
                        - account.Read_Only_Users
                      minimumCount: 1
                      disallowPipelineExecutor: false
                    approverInputs: []
                  timeout: 1d
              - parallel:
                  - step:
                      type: FlagConfiguration
                      name: FF 100
                      identifier: Youtube_100
                      spec:
                        feature: ALL_YOUTUBE_MODAL
                        environment: diegopereiraeng
                        instructions:
                          - identifier: AddRuleIdentifier
                            type: AddRule
                            spec:
                              priority: 100
                              distribution:
                                clauses:
                                  - op: segmentMatch
                                    attribute: ""
                                    values:
                                      - Beta_Users
                                bucketBy: email
                                variations:
                                  - variation: "OFF"
                                    weight: 0
                                  - variation: Captain_Canary
                                    weight: 0
                                  - variation: Feature_Flags
                                    weight: 100
                                  - variation: Italika
                                    weight: 0
                                  - variation: Gabs_GoT
                                    weight: 0
                                  - variation: Ion
                                    weight: 0
                      timeout: 10m
                      when:
                        stageStatus: Success
                        condition: <+pipeline.stages.FF_Youtube.execution.steps.Collect_Feedback_from_Analytics.output.outputVariables.result> == "ff"
                      failureStrategies: []
                  - step:
                      type: FlagConfiguration
                      name: Canary 100
                      identifier: Canary_100
                      spec:
                        feature: ALL_YOUTUBE_MODAL
                        environment: diegopereiraeng
                        instructions:
                          - identifier: SetFeatureFlagStateIdentifier
                            type: SetFeatureFlagState
                            spec:
                              state: "on"
                          - identifier: AddRuleIdentifier
                            type: AddRule
                            spec:
                              priority: 100
                              distribution:
                                clauses:
                                  - op: segmentMatch
                                    attribute: ""
                                    values:
                                      - Beta_Users
                                bucketBy: identifier
                                variations:
                                  - variation: "OFF"
                                    weight: 0
                                  - variation: Captain_Canary
                                    weight: 100
                                  - variation: Feature_Flags
                                    weight: 0
                                  - variation: Italika
                                    weight: 0
                                  - variation: Gabs_GoT
                                    weight: 0
                                  - variation: Ion
                                    weight: 0
                      timeout: 10m
                      when:
                        stageStatus: Success
                        condition: <+pipeline.stages.FF_Youtube.execution.steps.Collect_Feedback_from_Analytics.output.outputVariables.result> == "canary"
                      failureStrategies: []
          serviceDependencies: []
