pipeline:
  name: FF STATE PROMOTION
  identifier: FF_STATE_PROMOTION
  projectIdentifier: GIT_FLOW_DEMO
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: FF STATE DISCOVERY
        identifier: FF_STATE_DISCOVERY
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - stepGroup:
                  name: Discover Flag States
                  identifier: Discover_Flag_States
                  steps:
                    - step:
                        type: Run
                        name: Discover Flags
                        identifier: Discover_Flags
                        spec:
                          connectorRef: account.DockerHubDiego
                          image: diegokoala/python-utils:latest
                          shell: Python
                          command: |
                            import requests
                            import json
                            import os

                            # Retrieve the value of an environment variable
                            env_from_var_name = 'ENV_NAME_FROM'  
                            env_from_var_value = os.environ.get(env_from_var_name)
                            env_to_var_name = 'ENV_NAME_TO'  
                            env_to_var_value = os.environ.get(env_to_var_name)
                            # Check if the environment variable env from exists
                            if env_from_var_value is not None:
                                print(f"The value of {env_from_var_name} is {env_from_var_value}")
                            else:
                                print(f"{env_from_var_name} is not set.")

                            # Check if the environment variable env to exists
                            if env_to_var_value is not None:
                                print(f"The value of {env_to_var_name} is {env_to_var_value}")
                            else:
                                print(f"{env_to_var_name} is not set.")


                            # API endpoint and parameters
                            base_url = "https://app.harness.io/cf/admin/features"
                            headers = {
                                "x-api-key": '<+secrets.getValue("diegoapi")',  
                                "Content-Type": "application/json"
                            }
                            params = {
                                "accountIdentifier": "6_vVHzo9Qeu9fXvj-AcbCQ",
                                "orgIdentifier": "<+org.identifier>",
                                "projectIdentifier": "<+project.identifier>",
                                "pageSize": 200  # Adjust as needed
                            }

                            # Function to recursively fetch all feature flags for a given environment
                            def fetch_all_feature_flags(environment):
                                all_flags = []
                                page_index = 0

                                while True:
                                    params["environmentIdentifier"] = environment
                                    params["pageIndex"] = page_index
                                    response = requests.get(base_url, headers=headers, params=params)

                                    if response.status_code == 200:
                                        data = response.json()
                                        all_flags.extend(data["features"])
                                        # Check if there are more pages to fetch
                                        if page_index < data["pageCount"] - 1:
                                            page_index += 1
                                        else:
                                            break
                                    else:
                                        print(f"Error fetching data for {environment}: {response.status_code}")
                                        break

                                return all_flags

                            # Function to create a matrix of flag states and default values
                            def create_flag_matrix(flags):
                                matrix = {}
                                for flag in flags:
                                    identifier = flag["identifier"]
                                    matrix[identifier] = {
                                        "state": flag["envProperties"]["state"],
                                        "defaultOnVariation": flag["defaultOnVariation"],
                                        "defaultOffVariation": flag["defaultOffVariation"]
                                    }
                                return matrix

                            # Function to set environment variables
                            def set_env_variable(var_name, data):
                                os.environ[var_name] = json.dumps(data)
                                print(f"Environment variable '{var_name}' set.")

                            # Main execution
                            def main():
                                from_env = env_from_var_value
                                to_env = env_to_var_value

                                # Fetch all feature flags for both environments
                                from_flags = fetch_all_feature_flags(from_env)
                                to_flags = fetch_all_feature_flags(to_env)

                                # Create matrices for both environments
                                from_matrix = create_flag_matrix(from_flags)
                                to_matrix = create_flag_matrix(to_flags)

                                # Set environment variables for matrices
                                set_env_variable("FROM_MATRIX", from_matrix)
                                set_env_variable("TO_MATRIX", to_matrix)

                                # Compare the matrices and identify discrepancies
                                discrepancies = []
                                for identifier, from_info in from_matrix.items():
                                    to_info = to_matrix.get(identifier)
                                    if not to_info:
                                        discrepancies.append({
                                            "identifier": identifier,
                                            "issue": "Flag not found in 'to' environment.",
                                            "from_env": from_info
                                        })
                                        continue

                                    for key in from_info:
                                        if from_info[key] != to_info.get(key):
                                            discrepancy_detail = {
                                                "identifier": identifier,
                                                "issue": f"Mismatch in {key}",
                                                "from_env": from_info,
                                                "to_env": to_info
                                            }
                                            discrepancies.append(discrepancy_detail)

                                # Set environment variable for discrepancies
                                set_env_variable("DISCREPANCIES", discrepancies)

                                print(f"Comparing {from_env} to {to_env}...")
                                if discrepancies:
                                    print("Discrepancies found: %d" % len(discrepancies))
                                    for discrepancy in discrepancies:
                                        print(json.dumps(discrepancy, indent=4))
                                else:
                                    print("No discrepancies found. The feature flags are identical.")

                            if __name__ == "__main__":
                                main()
                          envVariables:
                            ENV_NAME_FROM: <+pipeline.variables.env_from>
                            ENV_NAME_TO: <+pipeline.variables.env_to>
                          outputVariables:
                            - name: DISCREPANCIES
                            - name: FROM_MATRIX
                            - name: TO_MATRIX
                          resources:
                            limits:
                              memory: 50Mi
                              cpu: 10m
                  stepGroupInfra:
                    type: KubernetesDirect
                    spec:
                      connectorRef: account.cddemose
                      namespace: default
              - step:
                  type: HarnessApproval
                  name: HarnessApproval_1
                  identifier: HarnessApproval_1
                  spec:
                    approvalMessage: Please review the following information and approve the pipeline progression
                    includePipelineExecutionHistory: true
                    isAutoRejectEnabled: false
                    approvers:
                      userGroups:
                        - account.New_Demo_Group
                      minimumCount: 1
                      disallowPipelineExecutor: false
                    approverInputs: []
                  timeout: 1d
              - stepGroup:
                  name: Copy States
                  identifier: Copy_States
                  steps:
                    - step:
                        type: Run
                        name: Copy Flags
                        identifier: Copy_Flags
                        spec:
                          connectorRef: account.DockerHubDiego
                          image: diegokoala/python-utils:latest
                          shell: Python
                          command: |-
                            # Retrieve the value of an environment variable
                            env_from_var_name = 'ENV_NAME'  
                            env_from_var_value = os.environ.get(env_from_var_name)
                          resources:
                            limits:
                              memory: 50Mi
                              cpu: 10m
                  stepGroupInfra:
                    type: KubernetesDirect
                    spec:
                      connectorRef: account.cddemose
                      namespace: default
            rollbackSteps: []
          serviceDependencies: []
        tags: {}
  variables:
    - name: env_from
      type: String
      description: ""
      required: false
      value: <+input>.default(qa).allowedValues(dev,qa,prd)
    - name: env_to
      type: String
      description: ""
      required: false
      value: <+input>.allowedValues(dev,qa,prd)
