pipeline:
  name: Harness-AIDA-CI
  identifier: HarnessAIDACI
  projectIdentifier: GIT_FLOW_DEMO
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: account.diegogithubapp
        repoName: harness-aida
        build: <+input>
  stages:
    - stage:
        name: Build Java
        identifier: Build_Java
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: RunTests
                  name: Run Tests - Package
                  identifier: Run_Tests_Package
                  spec:
                    language: Java
                    buildTool: Maven
                    args: package
                    runOnlySelectedTests: true
                    reports:
                      type: JUnit
                      spec:
                        paths:
                          - "**/*.xml"
              - step:
                  type: Sonarqube
                  name: Sonarqube
                  identifier: Sonarqube
                  spec:
                    mode: orchestration
                    config: default
                    target:
                      name: <+pipeline.properties.ci.codebase.repoName>
                      type: repository
                      variant: <+pipeline.properties.ci.codebase.build.build.spec.branch>
                      workspace: /harness
                    advanced:
                      log:
                        level: debug
                      fail_on_severity: high
                    settings:
                      repository_branch: <+pipeline.properties.ci.codebase.build.build.spec.branch>
                    auth:
                      access_token: <+secrets.getValue("account.harnesssonartoken")>
                      domain: http://sonar.harness-demo.site
                      ssl: true
                    tool:
                      java:
                        binaries: target/classes
                      project_key: <+pipeline.properties.ci.codebase.repoName>
