pipeline:
  name: IOS DevOps Mobile
  identifier: IOS_DevOps_Mobile
  projectIdentifier: GIT_FLOW_DEMO
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: account.Diego_Git
        repoName: ios_devops_mobile
        build: <+input>
  stages:
    - stage:
        name: Build IOS
        identifier: Build_IOS
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  name: Build
                  identifier: Build
                  spec:
                    shell: Sh
                    command: |
                      echo -n '<+secrets.getValue("apple_store_developer_apikey")>' > apple-store.p12
                    privileged: true
                    envVariables:
                      IPHONEOS_DEPLOYMENT_TARGET: 16.0.99
          platform:
            os: MacOS
            arch: Arm64
          runtime:
            type: Cloud
            spec: {}
