pipeline:
  name: IOS DevOps Mobile
  identifier: IOS_DevOps_Mobile
  projectIdentifier: GIT_FLOW_DEMO
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: account.Diego_Git
        repoName: ios_devops_mobile
        build: <+input>
  stages:
    - stage:
        name: Build IOS
        identifier: Build_IOS
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  name: Build
                  identifier: Build
                  spec:
                    shell: Sh
                    command: |-
                      #sudo xcode-select -switch /Applications/Xcode_14.2.0.app

                      ls -ltra

                      ls -ltra /Applications

                      sudo gem install cocoapods

                      pod install

                      keyfile=/private/tmp/harness/AuthKey.p8

                      pwd

                      echo "creating key file"

                      echo <+secrets.getValue("apple_store_developer_apikey")> > $keyfile

                      echo "created key file"

                      pwd

                      ls -ltra

                      cat $keyfile

                      xcodebuild -exportArchive -archivePath PlatformDevops.xcarchive -exportPath ./Artifact -exportOptionsPlist HarnessConfig.plist -authenticationKeyPath $keyfile -authenticationKeyID <+secrets.getValue("apple_store_api_key")> -authenticationKeyIssuerID <+secrets.getValue("apple_store_issuer_id")> -allowProvisioningUpdates

                      xcodebuild archive -workspace PlatformDevops.xcworkspace -scheme PlatformDevops -configuration Release -archivePath ./Artifact/PlatformDevops.xcarchive

                      xcodebuild -exportArchive -archivePath ./Artifact/PlatformDevops.xcarchive -exportPath ./Artifact/PlatformDevops.ipa -exportOptionsPlist HarnessConfig.plist

                      ls -ltra ./Artifact


                      altool --upload-app -f ./Artifact/PlatformDevops.ipa -t ios -u diegopereiraeng@gmail.com

                      xcodebuild -exportArchive -archivePath ./Artifact -exportPath YourExportPath -exportOptionsPlist HarnessConfig.plist
                    privileged: true
                    envVariables:
                      IPHONEOS_DEPLOYMENT_TARGET: 16.0.99
          platform:
            os: MacOS
            arch: Arm64
          runtime:
            type: Cloud
            spec: {}
