pipeline:
  name: pipeline-state-street-pr-test
  identifier: pipelinestatestreetprtest
  projectIdentifier: Platform_Engineering
  orgIdentifier: SE_Sandbox
  tags: {}
  stages:
    - stage:
        name: test
        identifier: test
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: echo "hellpo"
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
        tags: {}
