pipeline:
  name: CI-STO - Plugin Factory
  identifier: Plugin_Factory
  template:
    templateRef: Plugin_Build_Factory
    versionLabel: 0.0.1
    templateInputs:
      properties:
        ci:
          codebase:
            build: <+input>
      variables:
        - name: plugin_name
          type: String
          value: <+input>
        - name: repo_name
          type: String
          value: <+input>
        - name: image_name
          type: String
          value: <+input>
      stages:
        - stage:
            spec:
              execution:
                steps:
                  - step:
                      spec:
                        settings: {}
  tags: {}
  projectIdentifier: GIT_FLOW_DEMO
  orgIdentifier: default
