pipeline:
  name: CI-STO - GoLang Plugin Factory
  identifier: Plugin_Factory
  tags: {}
  template:
    templateRef: Plugin_Build_Factory
    versionLabel: 0.2.0
    templateInputs:
      properties:
        ci:
          codebase:
            build: <+input>
      stages:
        - stage:
            identifier: Plugin_E2E_Tests
            type: CI
            spec:
              execution:
                steps:
                  - step:
                      identifier: Plugin_Test
                      type: Plugin
                      spec:
                        settings: <+input>
      variables:
        - name: plugin_name
          type: String
          value: <+input>
        - name: repo_name
          type: String
          value: <+input>
        - name: image_name
          type: String
          value: <+input>
        - name: report_path
          type: String
          value: <+input>
  projectIdentifier: GIT_FLOW_DEMO
  orgIdentifier: default
