pipeline:
  name: Progressive Rollout Pipeline
  identifier: Progressive_Rollout_Pipeline
  projectIdentifier: GIT_FLOW_DEMO
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: Delivery Beta Users
        identifier: Delivery_Beta_Users
        description: ""
        type: FeatureFlag
        spec:
          execution:
            steps:
              - step:
                  type: JiraCreate
                  name: Jira Create - Progressive delivery Start
                  identifier: Jira_Create_Progressive_delivery_Start
                  spec:
                    connectorRef: BankingJira
                    projectKey: HD
                    issueType: Change
                    fields:
                      - name: Comment
                        value: Rollout starting with Beta 10%
                      - name: Summary
                        value: Progressive Rollout - Menu
                  timeout: 1d
              - step:
                  type: FlagConfiguration
                  name: Ten Percent Rollout
                  identifier: Ten_Percent_Rollout
                  spec:
                    feature: ALL_YOUTUBE_MODAL
                    environment: <+pipeline.variables.environment>
                    instructions:
                      - identifier: AddRuleIdentifier
                        type: AddRule
                        spec:
                          priority: 100
                          distribution:
                            bucketBy: identifier
                            clauses:
                              - op: segmentMatch
                                attribute: ""
                                values:
                                  - Beta_Users
                            variations:
                              - variation: "OFF"
                                weight: 90
                              - variation: Captain_Canary
                                weight: 0
                              - variation: Feature_Flags
                                weight: 10
                              - variation: Italika
                                weight: 0
                              - variation: Gabs_GoT
                                weight: 0
                              - variation: Ion
                                weight: 0
                      - identifier: SetFeatureFlagStateIdentifier
                        type: SetFeatureFlagState
                        spec:
                          state: "on"
                  timeout: 10m
              - step:
                  type: JiraUpdate
                  name: Jira Forty Percent
                  identifier: Jira_Fifty_Percent
                  spec:
                    connectorRef: BankingJira
                    issueKey: <+pipeline.stages.Delivery_Beta_Users.execution.steps.Jira_Create_Progressive_delivery_Start.issue.key>
                    transitionTo:
                      transitionName: ""
                      status: In Progress
                    fields:
                      - name: Comment
                        value: Rollout Forty Percent
                  timeout: 1d
              - step:
                  type: FlagConfiguration
                  name: Fourty Percent
                  identifier: Fifty_Percent
                  spec:
                    feature: ALL_YOUTUBE_MODAL
                    environment: <+pipeline.variables.environment>
                    instructions:
                      - identifier: AddRuleIdentifier
                        type: AddRule
                        spec:
                          priority: 100
                          distribution:
                            bucketBy: identifier
                            clauses:
                              - op: segmentMatch
                                attribute: ""
                                values:
                                  - Beta_Users
                            variations:
                              - variation: "OFF"
                                weight: 50
                              - variation: Captain_Canary
                                weight: 0
                              - variation: Feature_Flags
                                weight: 50
                              - variation: Italika
                                weight: 0
                              - variation: Gabs_GoT
                                weight: 0
                              - variation: Ion
                                weight: 0
                  timeout: 10m
              - step:
                  type: ShellScript
                  name: Tests
                  identifier: Tests
                  spec:
                    shell: Bash
                    onDelegate: true
                    source:
                      type: Inline
                      spec:
                        script: |-
                          echo "Performing Tests"

                          export result="true"
                    environmentVariables: []
                    outputVariables:
                      - name: test_result
                        type: String
                        value: result
                  timeout: 10m
              - step:
                  type: JiraApproval
                  name: Jira Approval
                  identifier: JiraApproval
                  spec:
                    connectorRef: BankingJira
                    projectKey: HD
                    issueType: Change
                    approvalCriteria:
                      type: KeyValues
                      spec:
                        matchAnyCondition: true
                        conditions:
                          - key: Status
                            operator: equals
                            value: Approved
                    rejectionCriteria:
                      type: KeyValues
                      spec:
                        matchAnyCondition: true
                        conditions: []
                    issueKey: <+pipeline.stages.Delivery_Beta_Users.execution.steps.Jira_Create_Progressive_delivery_Start.issue.key>
                  timeout: 1d
                  when:
                    stageStatus: Success
                    condition: <+execution.steps.Tests.output.outputVariables.test_result> == "false"
                  failureStrategies: []
              - step:
                  type: HarnessApproval
                  name: Full Rollout Approval
                  identifier: Full_Rollout_Approval
                  spec:
                    approvalMessage: Please review the following information and approve the pipeline progression
                    includePipelineExecutionHistory: true
                    approvers:
                      userGroups:
                        - account._account_all_users
                      minimumCount: 1
                      disallowPipelineExecutor: false
                    approverInputs: []
                  timeout: 10m
              - step:
                  type: FlagConfiguration
                  name: Full Rollout
                  identifier: Full_Rollout
                  spec:
                    feature: ALL_YOUTUBE_MODAL
                    environment: <+pipeline.variables.environment>
                    instructions:
                      - identifier: AddRuleIdentifier
                        type: AddRule
                        spec:
                          priority: 100
                          distribution:
                            bucketBy: identifier
                            clauses:
                              - op: segmentMatch
                                attribute: ""
                                values:
                                  - Beta_Users
                            variations:
                              - variation: "OFF"
                                weight: 0
                              - variation: Captain_Canary
                                weight: 0
                              - variation: Feature_Flags
                                weight: 100
                              - variation: Italika
                                weight: 0
                              - variation: Gabs_GoT
                                weight: 0
                              - variation: Ion
                                weight: 0
                  timeout: 10m
                  when:
                    stageStatus: Success
                    condition: <+execution.steps.Tests.output.outputVariables.test_result> == "true"
                  failureStrategies: []
              - step:
                  type: HarnessApproval
                  name: Harness Approval
                  identifier: HarnessApproval
                  spec:
                    approvalMessage: Please review the following information and approve the pipeline progression
                    includePipelineExecutionHistory: true
                    approvers:
                      userGroups:
                        - _project_all_users
                      minimumCount: 1
                      disallowPipelineExecutor: false
                    approverInputs: []
                  timeout: 1d
              - step:
                  type: FlagConfiguration
                  name: Rollback
                  identifier: Rollback
                  spec:
                    feature: ALL_YOUTUBE_MODAL
                    environment: <+pipeline.variables.environment>
                    instructions:
                      - identifier: AddRuleIdentifier
                        type: AddRule
                        spec:
                          priority: 100
                          distribution:
                            bucketBy: identifier
                            clauses:
                              - op: segmentMatch
                                attribute: ""
                                values:
                                  - Beta_Users
                            variations:
                              - variation: "OFF"
                                weight: 100
                              - variation: Captain_Canary
                                weight: 0
                              - variation: Feature_Flags
                                weight: 0
                              - variation: Italika
                                weight: 0
                              - variation: Gabs_GoT
                                weight: 0
                              - variation: Ion
                                weight: 0
                      - identifier: SetFeatureFlagStateIdentifier
                        type: SetFeatureFlagState
                        spec:
                          state: "off"
                  timeout: 10m
                  failureStrategies: []
                  when:
                    stageStatus: All
                    condition: <+pipeline.stages.Delivery_Beta_Users.execution.steps.HarnessApproval.output.approvalActivities[0].action> == "REJECT" || <+pipeline.stages.Delivery_Beta_Users.execution.steps.Full_Rollout_Approval.output.approvalActivities[0].action> == "REJECT"
              - parallel:
                  - step:
                      type: JiraUpdate
                      name: Jira Done
                      identifier: Jira_Done
                      spec:
                        connectorRef: BankingJira
                        issueKey: <+pipeline.stages.Delivery_Beta_Users.execution.steps.Jira_Create_Progressive_delivery_Start.issue.key>
                        transitionTo:
                          transitionName: ""
                          status: Done
                        fields:
                          - name: Comment
                            value: Full Rollout with Success \n Harness Feature Flags
                      timeout: 1d
                  - step:
                      type: JiraUpdate
                      name: Jira Canceled
                      identifier: Jira_Canceled
                      spec:
                        connectorRef: BankingJira
                        issueKey: <+pipeline.stages.Delivery_Beta_Users.execution.steps.Jira_Create_Progressive_delivery_Start.issue.key>
                        transitionTo:
                          transitionName: ""
                          status: Rejected
                        fields:
                          - name: Comment
                            value: Rollout Failed - Rollback with Success
                      timeout: 1d
                      when:
                        stageStatus: All
                        condition: <+pipeline.stages.Delivery_Beta_Users.execution.steps.HarnessApproval.output.approvalActivities[0].action> == "REJECT" || <+pipeline.stages.Delivery_Beta_Users.execution.steps.Full_Rollout_Approval.output.approvalActivities[0].action> == "REJECT"
                      failureStrategies: []
    - stage:
        name: Customer Progressive Delivery
        identifier: Customer_Progressive_Delivery
        description: ""
        type: FeatureFlag
        spec:
          execution:
            steps:
              - step:
                  type: FlagConfiguration
                  name: Ten Percent Customers
                  identifier: Ten_Percent_Customers
                  spec:
                    feature: Menu_Version
                    environment: <+pipeline.variables.environment>
                    instructions:
                      - identifier: AddRuleIdentifier
                        type: AddRule
                        spec:
                          priority: 100
                          distribution:
                            bucketBy: identifier
                            clauses:
                              - op: segmentMatch
                                attribute: ""
                                values:
                                  - Beta_Users
                            variations:
                              - variation: V1
                                weight: 90
                              - variation: V2
                                weight: 10
                  timeout: 10m
              - step:
                  type: FlagConfiguration
                  name: Fifty Percent Customers
                  identifier: Fifty_Percent_Customers
                  spec:
                    feature: Menu_Version
                    environment: <+pipeline.variables.environment>
                    instructions:
                      - identifier: AddRuleIdentifier
                        type: AddRule
                        spec:
                          priority: 100
                          distribution:
                            bucketBy: identifier
                            clauses:
                              - op: segmentMatch
                                attribute: ""
                                values:
                                  - Beta_Users
                            variations:
                              - variation: V1
                                weight: 50
                              - variation: V2
                                weight: 50
                  timeout: 10m
              - step:
                  type: FlagConfiguration
                  name: Full Rollout
                  identifier: FlagConfiguration
                  spec:
                    feature: Menu_Version
                    environment: <+pipeline.variables.environment>
                    instructions:
                      - identifier: AddRuleIdentifier
                        type: AddRule
                        spec:
                          priority: 100
                          distribution:
                            bucketBy: identifier
                            clauses:
                              - op: segmentMatch
                                attribute: ""
                                values:
                                  - Beta_Users
                            variations:
                              - variation: V1
                                weight: 0
                              - variation: V2
                                weight: 100
                  timeout: 10m
  variables:
    - name: environment
      type: String
      default: diegopereiraeng
      description: ""
      value: <+input>.allowedValues(diegopereiraeng,gacerioni,poharav,andymarshallff,riickster)
