pipeline:
    name: Semsedia
    identifier: Semsedia
    template:
        templateRef: testbug1
        versionLabel: v1
        templateInputs:
            properties:
                ci:
                    codebase:
                        build: <+input>
            variables:
                - name: tag
                  type: String
                  value: <+input>
                - name: ffkey
                  type: String
                  value: <+input>
                - name: virtualPath
                  type: String
                  value: <+input>
                - name: gitEvent
                  type: String
                  value: <+input>
                - name: target
                  type: String
                  value: <+input>
                - name: branch
                  type: String
                  value: <+input>
    tags: {}
    projectIdentifier: GIT_FLOW_DEMO
    orgIdentifier: default
