pipeline:
  name: Java Build
  identifier: test
  projectIdentifier: GIT_FLOW_DEMO
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: account.Diego_Git
        repoName: kafka
        build: <+input>
  stages:
    - stage:
        name: kafka build
        identifier: kafka_build
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
          buildIntelligence:
            enabled: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Build
                  identifier: Build
                  spec:
                    connectorRef: account.DockerHubDiego
                    image: gradle:jdk17-jammy
                    shell: Sh
                    command: |-
                      java --version

                      ./gradlew clean releaseTarGz -x spotlessJava -x spotlessCheck
