apiVersion: cert-manager.io/v1 
kind: Issuer 
metadata: 
name: ca-issuer-mongo 
  namespace: prod 
spec: 
  ca: 
    secretName: ca-key-pair 
--- 
apiVersion: cert-manager.io/v1 
kind: Certificate 
metadata: 
  name: cert-manager-certificate 
  namespace: prod 
spec: 
  secretName: mongodb-tls 
  issuerRef: 
    name: ca-issuer-mongo 
    kind: Issuer 
  commonName: "*.mongo-replicaset-svc.mongodb.svc.cluster.local" 
  dnsNames: 
  - "*.mongo-replicaset-svc.mongodb.svc.cluster.local" 
  - mongo-replicaset-0.com 
  - mongo-replicaset-1.com 
  - mongo-replicaset-2.com 