# charts/mongodb/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}-mongodb-secret
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  username: {{ .Values.mongodbUsername | b64enc }}
  password: {{ .Values.mongodbPassword | b64enc }}