# charts/mongodb/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-mongodb
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.name }}-mongodb
  ports:
  - name: mongodb
    port: 27017
    targetPort: 27017
  type: ClusterIP