apiVersion: v1
kind: Secret
namespace: mongodb-atlas-system
metadata:
  name: mongodb-atlas-operator-api-key
stringData:
  orgId: "638e726aa18b763a4f565fb4"
  publicApiKey: "iegpscci"
  privateApiKey: "81d4dfac-75c0-45fb-904d-8c24e36c7ddb"
