apiVersion: apps/v1
kind: Deployment
metadata:
  name: backstage
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      app: backstage
  replicas: 1
  template:
    metadata:
      labels:
        app: backstage
    spec:
      containers:
      - name: backstage
        image: backstage/backend:latest
        ports:
        - containerPort: 3030
        env:
        - name: POSTGRES_URI
          value: postgres://{{ .Values.postgresUsername }}:{{ .Values.postgresPassword }}@postgres:5432/{{ .Values.postgresDb }}
      - name: postgres
        image: postgres:12
        ports:
        - containerPort: 5432
