apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.name }}
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      containers:
      - name: {{ .Values.name }}
        image: backstage/backend:latest
        ports:
        - containerPort: 3030
        env:
        - name: MONGO_URI
          value: mongodb://{{ .Values.mongodbUsername }}:{{ .Values.mongodbPassword }}@mongodb.{{ .Values.namespace }}.svc.cluster.local:27017/backstage
        - name: ELASTICSEARCH_URLS
          value: {{ .Values.ELASTICSEARCH_URLS }}
        - name: ELASTICSEARCH_PASSWORD
          value: {{ .Values.ELASTICSEARCH_PASSWORD }}
      - name: mongodb
        image: mongo:4.4
        ports:
        - containerPort: 27017
---
apiVersion: v1
kind: Namespace
metadata:
  name: tools
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.name }}
  ports:
  - name: http
    port: 3030
    targetPort: 3030
  type: ClusterIP
---
